# Generated by Django 5.2.4 on 2025-08-31 07:28

import app.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('login', models.CharField(max_length=100, unique=True)),
                ('password', models.CharField(max_length=1000)),
                ('email', models.CharField(max_length=100)),
                ('admin', models.BooleanField(blank=True, default=False)),
                ('files_storage_size', models.IntegerField(blank=True, default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(max_length=200)),
                ('login', models.CharField(max_length=100, unique=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.user')),
            ],
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_content', models.FileField(upload_to=app.models.user_directory_path)),
                ('file_name', models.CharField(max_length=255)),
                ('file_link', models.CharField(max_length=200)),
                ('file_size', models.IntegerField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('last_upload_date', models.DateTimeField(blank=True)),
                ('comment', models.CharField(max_length=300)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.user')),
            ],
        ),
    ]
